name: Test i686 Compatibility

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  test-i686:
    runs-on: ubuntu-latest
    container:
      image: i386/alpine:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go and dependencies
        run: |
          apk update
          apk add go git

      - name: Run Go tests
        env:
          GOARCH: 386  # Ensure we're targeting 32-bit if needed
        run: |
          go version
          make test
