name: Test i686 Compatibility

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  test-i686:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Alpine Linux Environment
        uses: jirutka/setup-alpine@v1
        with:
          arch: i686  # Set architecture to i686
          branch: edge # Use the latest Alpine branch (optional)
          packages: > # Install required packages
            docker
            go
            nodejs
                npm

      - name: Run Tests
        run: make test