name: Test i686 Compatibility

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  test-i686:
    runs-on: ubuntu-latest
    container: i386/node  # Use a 32-bit Node.js image

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl gcc make

      - name: Install Go
        run: |
          curl -OL https://golang.org/dl/go1.21.5.linux-386.tar.gz
          tar -C /usr/local -xzf go1.21.5.linux-386.tar.gz
          echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
          source ~/.bashrc
          /usr/local/go/bin/go version  # Verify installation

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          make test